/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_acceuil (void);
GtkWidget* create_gestion (void);
GtkWidget* create_fenetre_ajout (void);
GtkWidget* create_login (void);
